### ISSUE TITLE
Required fields taken

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#22] opened 2016-10-17 11:18 UTC

**Comment by liamoc** [comment] 2016-10-20 16:17
Actually, this is not a bug, it's intended behaviour. The fix commit breaks soundness of the subtyping relation, so you'll want to revert that.

**Comment by liamoc** [comment] 2016-10-20 16:17
You're allowed to "take" discardable fields from records as part of the subtyping relation now.

**Comment by zilinc** [comment] 2016-10-20 22:59
```
type ExState
type RR c a b = (c, <Success a | Error b>)
type OSBuffer

type Ext2Superblock = {
    inode_count             : U32,
    magic                   : U16
}

deserialise_Ext2Superblock: (ExState, OSBuffer!, U32) -> RR ExState (Ext2Superblock, U32) ()

free_Ext2Superblock  : (ExState, Ext2Superblock take (..)) -> ExState
free_Ext2Superblock' : (ExState, Ext2Superblock) -> ExState

foo : #{ex: ExState, buf_super : OSBuffer} -> ExState
foo #{ex, buf_super} = 
  let (ex, res) = deserialise_Ext2Superblock (ex, buf_super, 0) !buf_super
  in res
  | Success (super, _) -> 
      free_Ext2Superblock (ex, super)  -- super is all-untaken
  | Error () -> ex
```
This exampled didn't typecheck before my last change.

**Comment by zilinc** [comment] 2016-10-20 23:41
reverted in ee00083

**Comment by zilinc** [comment] 2016-10-27 02:43
@liamoc Still don't get why in `tests/pass_ticket-e22-2.cogent` the pattern var `super`of type `?11` is inferred to be `Ext2Superblock take (..)` instead of all untaken. In the case of `tests/pass_ticket-e22-3.cogent`, it causes the member op to fail.

**Comment by liamoc** [comment] 2016-10-27 02:54
This is a separate bug than the previous one. I see why this is happening but I'm struggling to figure out a nice way to fix it. Basically, the free call is introducing a constraint like

     ?11 :< Ext2Superblock take (..)

And the member call only generates a constraint like:

     { magic : U16 } :>~ ?11

which is only checked once ?11 is resolved.

This may require me to design the solver quite differently. It'll need some serious thinking.

**Comment by liamoc** [comment] 2016-10-27 04:06
OK, I think I've figured out the changes I need to make, although it's quite a significant amount of refactoring. Might take me a while.

**Comment by liamoc** [comment] 2016-10-27 13:56
OK, If you want you can merge my tc-new branch. It fixes this bug.

I've gotten rid of those Partial or :<~ constraints entirely. Now we have just subtyping (and a separate constraint Upcastable specifically for integers).

Subtyping, however, is now a relation on _type fragments_, which may be:

  * A `TCType` (a unification variable or a concrete type)
  * A partially-specified variant type.
  * A partially-specified record type.

This type is _non-recursive_, and we _never_ instantiate type variables to type fragments (meaning that our substitution type still is effectively a map from variables to `TCType`s).

Now the solver will group regular and "partial" subtyping constraints together, and solve them together. This solves this bug as this bug is caused by the (non-partial) subtyping constraints being solved first -- then the partial constraints fail. We need to come up with solutions that satisfy all the constraints, and a solution that satisfies just the non-partial subtyping constraints will not be a safe solution for the partial ones.. hopefully that makes sense.

The code in the solver is now quite repetitive though, so if anyone wants to have a go at refactoring it (while preserving semantics) it might be a nice thing.

**Comment by liamoc** [comment] 2016-10-28 06:01
OK, I'm in the process of writing up this algorithm now, and I realised there's probably still a bug here.

The general gist of the solver is that it groups subtyping constraints by their variable (and whether it occurs on the left or right hand side). So for example all constraints of the form `?x :< ...`. Then it computes the GLB (or LUB) of all the types on the other side to get the result. 

The possible bug is that if there are flex-flex constraints, e.g `?x :< ?y`, we currently _don't_ include them in the constraint set and delay them until later. This means that it may be possible to find a program for which the flex-rigid constraints give a solution for `?x` and `?y` that doesn't satisfy that flex-flex constraint.

The fix is, if we have only one flex-rigid constraint `?x :< T`, we should _not_ apply the substitution `x |-> T`  if there are flex-flex constraints `?x :< ?y` still in the set.

Posting this mostly as a reminder to myself to try to fix this possible problem and see if it breaks anything. I haven't found an example program that breaks, but the algorithm may give surprising results, I'm not sure.

**Comment by liamoc** [comment] 2016-11-01 13:38
OK, I've convinced myself that it's safe to delay flex-flex constraints.

Because, if we have a solution for `?x`, we will substitute right away, so the `?x :< ?y` constraint will become a flex-rigid `... :< ?y` constraint which will inform solving for `?y`. Because our subtyping relationship is basically a lattice, it shouldn't matter if `?x` or `?y` is solved first. So delaying until we solve either one is allowed.

Should we close this issue?

**Comment by zilinc** [comment] 2016-11-01 14:47
No, the same symptom (... of type ... is required but has been taken) appears again in ext2. I'm still working on shrinking the code.

**Comment by zilinc** [comment] 2016-11-07 01:53
Under d10fa13, for file `pass_ticket-e22-4.cogent`, the `Unsat` is from `?11 put (..) :< ?10`

**Comment by liamoc** [comment] 2016-11-11 14:32
Alright, I stepped through (a further simplified version of) this example, running the algorithm by hand. I figured out what's wrong. The constraints you end up with are something like:

       ?1 :< { a : U32, b : WordArray U32 } take b
       ?1 :< ?{a : U32}
       ?0 :< { a : U32, b : WordArray U32 } take (a, b)
       ?0 :< ?1 

In this scenario, the solver sees a "no-brainer" opportunity for `?0` that is not correct. I guess I was wrong when I said earlier that delaying flex-flex constraints is OK.

**Comment by liamoc** [comment] 2016-11-11 19:08
OK, I've pushed a series of commits to my fork. Merge whenever. It passes all the pass_ tests (including one test that should never have been passing, but I fixed the test case).

Now it will not solve (i.e. generate a substitution for) any "no-brainer" constraint while there are still flex/flex constraints about the same variable (for this check we ignore reflexive constraints `?x :< ?x`). We also make an exception here for numeric types. Seeing as, for numeric types, subtyping is just equality, we solve all subtyping no-brainers for numeric types before we try and guess the numeric types from the cast.

This doesn't seem to have caused any regressions. 

I'm also working on better handling of constraints like

    ?x take f :< {...}

Now this transforms into:

    ?x :< {...} put f

And similar. I haven't finished all the `rule` cases for this yet, but it already seems to pass all the tests. I'm not sure how commonly these constraints come up so fully implementing this may not be urgent.

**Comment by liamoc** [comment] 2016-11-12 07:56
After some testing, I think transforming `?x take f :< {...}` to `?x :< {...} put f` etc. is not needed. Seeing as I'm not convinced such transformations are sound in all cases, I removed it for now. Let me know if you run into incompleteness cases.

Now it will simply not solve any system of constraints involving such type operators until they can be evaluated. 

Also, I've discovered a really simple way to explain how this algorithm works now which suggests I'm on the right track.

**Comment by zilinc** [comment] 2016-11-12 13:25
With this version of compiler, I got tons of `leftover constraints` when compiling ext2..

**Comment by liamoc** [comment] 2016-11-12 18:33
Can you show me what constraints are left over / add test cases?

**Comment by zilinc** [comment] 2016-11-13 00:55
All of the form `?1 :< ?2` and for the majority `?1 :< ?1`. Test cases come later.

**Comment by zilinc** [comment] 2016-11-13 01:37
For the test above, I found it hard to shrink further. In particular, if you uncomment the `= U32`, it passes.

**Comment by zilinc** [comment] 2016-11-13 23:12
Yuck, forgot to add file... see 077ef3969e57fc5e

**Comment by liamoc** [comment] 2016-11-17 03:58
Ah, this is an interesting case. Not too tricky to solve.

Basically, abstract types right now assume their parameters are invariant w.r.t. subtyping. I could actually assume covariance, I think, seeing as C abstract types are unlikely to use the types in negative position..

The problem is that right now that generates constraints of the form: `B :< ?x :& ?x :< B` to enforce the _invariance_. Normally this doesn't cause a problem, but in that case (because of the nested if) you end up with a duplicate of these constraints, it will end up doing LUB, producing something like: `B :< ?x :& ?x :< ?y :& ?y :< ?x :& ?y :< B` . The presence of the flex-flex constraints then prevents the flex-rigid "no brainer" constraints from ever being solved.

How to fix? Well, simple solution is to make all abstract types covariant. Then the cycles go away.

More sophisticated and durable solution is to add a specific _equality_ type constraint specifically for invariant parameters. This equality constraint is solved before subtyping even comes into the picture (including flex-flex substitution).

Right now I'm leaning towards covariant abstract types, seeing as we probably would want that anyway?

**Comment by zilinc** [comment] 2016-11-17 10:58
I merged. So far it's alright. Let's see if there's a problem with covariance. Not sure if you plan to implement the graph representation at all, but with a graph, it would be easy to identify and flatten cycles.

**Comment by liamoc** [comment] 2016-11-17 11:07
Yep, that's true, although right now with the covariance I don't think we generate cycles (by cycles, I only mean cycles between unification variables. Cycles involving concrete types aren't problematic).

**Comment by liamoc** [comment] 2016-11-17 12:21
BTW, I just pushed another commit that will make the type checker even more strict about some of these constraints.

Now if there is a flex-rigid constraint that mentions a flex-flex variable, e.g `{ f : ?x } :< ?y`, it will solve `?y` before solving `?x` because the solution to `?y` will affect the possible solution for `?x`. It wasn't doing this before, but adding this extra strictness didn't seem to break anything so I think it's more principled to do it this way.

**Comment by zilinc** [comment] 2016-11-17 14:12
Merged.

**Comment by zilinc** [comment] 2016-11-17 14:20
Oops! Merged to early... now it crashes with `Panic: invalid type to normaliseT` when compiling ext2. The last commit was Okay though.

**Comment by liamoc** [comment] 2016-11-17 14:21
hm, ok. Can you track down where it happens?

**Comment by zilinc** [comment] 2016-11-17 14:22
Sure. I'll do.

**Comment by zilinc** [comment] 2016-11-17 16:07
Still quite huge for debugging, but at least in a single file...

**Comment by liamoc** [comment] 2016-11-18 00:19
OK, looking at the substitution I can see something is wrong:

A number of variables have unification variable 65 in their solution:

      76 |-> ((?65) put buf)!
      77 |-> U32
      78 |-> ((?65) put buf)!
      79 |-> U32
      80 |-> (WordArray U32, U32)
      81 |-> #{ arr : WordArray U32
              , frm : WordArrayIndex
              , to : WordArrayIndex
              , f : WordArrayMapNoBreakF U32 U32 ()
              , acc : U32
              , obsv : () }
      82 |-> WordArray U32
      83 |-> U32
      84 |-> ((?65) put buf)!
      85 |-> U32
      86 |-> ((?65) put buf)!
      87 |-> ElemAO U32 U32 () -> (U32, U32)
      88 |-> U32
      89 |-> ((?65) put buf)!

But `?65` has a solution too:

    65 |-> { blockptr : BlockPtr, buf : Option OSBuffer, offset : U32 } take buf

So maybe i'm not applying substitutions right in some weird corner case..

**Comment by liamoc** [comment] 2016-11-18 00:52
I figured it out. I  currently combine substitutions like this


     mappend a@(Subst a') b@(Subst b')
        = Subst (fmap (apply b) a' <> fmap (apply a) b')

But this doesn't work if `a` mentions variables eliminated by `b`..

**Comment by liamoc** [comment] 2016-11-18 01:04
I think it should just work (tm) now.

**Comment by liamoc** [comment] 2016-11-18 01:14
Incidentally, I have serious style reservations as to how they've designed the gum library.

In that example file, the inferencer can't figure out the type parameters to those functions because they applied `!`s to the type variables. They shouldn't do that, they should constrain by kind instead.

e.g. they have this:

    type Seq32Param acc obsv rbrk = #{
      frm: U32,
      to: U32,
      step: U32,
      f: Seq32_body acc obsv rbrk,
      acc: acc,
      obsv: obsv!
    }

But this shouldn't `!` the `obsv` parameter. They should just require that the `obsv` parameter is shareable.


  seq32: all (acc,obsv :< DS,rbrk).  Seq32Param acc obsv rbrk -> LRR acc rbrk

If you do it that way, the type inference has a chance of figuring it out.

The other option is to try and come up with some solver smarts for solving constraints modulo `!`.

**Comment by zilinc** [comment] 2016-11-18 02:32
Disregarding the type inference problem, is it a flawed way of defining functions?

**Comment by liamoc** [comment] 2016-11-18 02:32
Only in that inference will always be impossible because you're throwing away type information.

**Comment by zilinc** [comment] 2016-11-18 03:06
Turning it into a separate ticket. (#29)

**Comment by zilinc** [comment] 2016-11-18 04:22
Another instance of "required field taken" added.

**Comment by liamoc** [comment] 2016-11-18 04:30
This is a different bug to the last similar case. Note that the constraint that causes the error:

    { inode_count : U32, free_inode_count : U32 } :< ?{ free_inode_count : ?4 } take free_inode_count

actually should be true..

This should be allowed. It should emit a `Drop U32` constraint and allow you to passively drop the field. So I'm not sure why this is erroring.

**Comment by liamoc** [comment] 2016-11-18 04:54
I realised I had the subtyping around the wrong way for taken fields of records, and there was another bug where it do a flex-flex substitution if there was a `!` involved which is a no-no. Both are fixed now.

**Closed** 2016-11-18 06:11 UTC
Labels: bug, cdsl2-new-tc
